# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.patch_response_updated import PatchResponseUpdated


class PatchResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PatchResponse - a model defined in OpenAPI

        id: The id of this PatchResponse.
        updated: The updated of this PatchResponse.
    """

    id: int = Field(alias="id")
    updated: PatchResponseUpdated = Field(alias="updated")

PatchResponse.update_forward_refs()
