version: "3.6"

services:
  backend:
    container_name: craftman_backend
    build:
      context: ./backend/
      target: service
    ports:
      - "8080:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080

  postgres:
    build:
      context: ./postgres/
    container_name: craftman_postgres
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/postgres.env
