version: "3.6"

services:
  frontend:
    build:
      context: frontend
      args:
        REACT_APP_API_URL: "http://localhost:3000"

    ports:
      - "80:80"

  backend:
    build: backend
    ports:
      - "3000:80"

  mysql:
    build: mysql
    env_file:
      - ./mysql/mysql.env
    volumes:
      - ./mysql/data:/var/lib/mysql
