version: "3.6"

services:
  frontend:
    build:
      context: frontend
      args:
        REACT_APP_API_URL: "http://localhost:3000"

    ports:
      - "80:80"

  backend:
    build: backend
    environment:
      POSTGRES_DB: craftmen
    ports:
      - "3000:80"

  db:
    image: postgis/postgis:latest
    volumes:
      - ./postgres/sql:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: craftmen
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
