# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PatchResponseUpdated(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PatchResponseUpdated - a model defined in OpenAPI

        max_driving_distance: The max_driving_distance of this PatchResponseUpdated.
        profile_picture_score: The profile_picture_score of this PatchResponseUpdated.
        profile_description_score: The profile_description_score of this PatchResponseUpdated.
    """

    max_driving_distance: float = Field(alias="maxDrivingDistance")
    profile_picture_score: float = Field(alias="profilePictureScore")
    profile_description_score: float = Field(alias="profileDescriptionScore")
