version: "3.8"

services:
  postgres:
    image: postgis/postgis:latest
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - postgres.env